<h2>ML Tutorial</h2>

<ul style="list-style-type: none;">
	<li><a href="<?= $this->url('machinelearning', ['action' => 'index']) ?>" >Home</a></li>
	<li><a href="<?= $this->url('machinelearning', ['action' => 'basics']) ?>">Basics</a></li>
	<li><a href="<?= $this->url('machinelearning', ['action' => 'classification']) ?>">ML Algorithms − Classification</a></li>
	<li><a href="<?= $this->url('machinelearning', ['action' => 'regression']) ?>">ML Algorithms − Regression</a></li>
	<li><a href="<?= $this->url('machinelearning', ['action' => 'clustering']) ?>">ML Algorithms − Clustering</a></li>

</ul>