<?php
	$title = 'Data Structures';
	$this->headTitle($title);
	use Laminas\Db\Adapter\AdapterInterface;
	use Laminas\Db\Adapter\Driver\ResultInterface;
	use Laminas\Db\Sql\Sql;

	$adapter = new Laminas\Db\Adapter\Adapter([
	    'driver'   => 'Pdo_Sqlite',
	    'database' => __DIR__ . '/../../../../../data/rtutordb',
	]);
?>


<div class="container-fluid">
	<div class="row filter_data">
        <?php
	        $statement = $adapter->query("SELECT * FROM course WHERE course_tag='datastructures'");
	        $results = $statement->execute();
	        foreach($results as $row)
	          {
        ?>
        <div style="height:450px; width: 100%">
	        <div class="jumbotron jumbotron-fluid text-center" style="background-color: #336699">
				<div>
					<p align="center" style="color: black; font-size: 20px;"><strong><?php echo $row['course_category']; ?></strong></p>
					<h1 class="display-3 text-white"><?php echo $row['course_name'] ?></h1>
					<p>Job Title : <?php echo $row['course_jobtitle']?><br />
		             Course Level : <?php echo $row['course_level'] ?> <br />
		             Creator : <?php echo $row['course_creator'] ?><br /></p>
		             <p><a href="<?php echo $row['course_tag'] ?>/basics" class="btn btn-outline-warning">View Course</a></p>
		             <?php $id=$row['course_id'] ?>
				</div>
			</div> 
        </div>

          <?php
          }
          ?>
    </div>

</div>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-4 box">
			<h3>What You will Learn</h3>
			<p>This is an Intermediate python tutorial</p>
			<ul style="list-style-type: none;">
				<li>Home</li>
				<li>Basics</li>
				<li>Greedy</li>
				<li>Divide And Conquer</li>
				<li>Dynamic programming</li>
			</ul>
		</div>	
		<div class="col-md-4 box">
			<h3>Requirements</h3>
			<p>Before proceeding with this tutorial, you should have a basic understanding of C programming language, text editor, and execution of programs, etc.</p>
		</div>	
		<div class="col-md-4 box">
			<h3>Description</h3>
			<p>Data Structures are the programmatic way of storing data so that data can be used efficiently. Almost every enterprise application uses various types of data structures in one or the other way. This tutorial will give you a great understanding on Data Structures needed to understand the complexity of enterprise level applications and need of algorithms, and data structures.</p>
		</div>	
	</div>
</div>

<div class="container-fluid pt-3"  style="margin-bottom: 10px;">
	<h1 class="text-center">Reviews Of This Course</h1>	
	<center>
		<a  href="<?= $this->url('review', ['action' => 'add', 'id' => $id]) ?>" class="btn btn-outline-primary">Write a Review</a>
	</center>
	<br>
	
	<?php
        $statement = $adapter->query("SELECT * FROM reviews WHERE course_id=$id");
        $results = $statement->execute();
        foreach($results as $row)
          {
    ?>
    <div class="media border p-3">
	    <div class="media-body">
	      <h4><?php echo $row['content']; ?></h4>
	      <?php if ($row['user_id'] == $identity->id) {
	      	?>
	      	<p>Created by You.</p>
	      <a href="<?= $this->url('review', ['action' => 'edit', 'id' => $row['id']]) ?>" class="btn btn-outline-success">Edit Review</a>
	      <a href="<?= $this->url('review', ['action' => 'delete', 'id' => $row['id']]) ?>" class="btn btn-outline-danger">Delete Review</a>
	     <?php }
	     	else{?>
	     		<p>Created by User with Id: <?php echo $row['user_id']; ?></p>
	     <?php
	 		}
	      ?>
	    </div>
	</div>
	<br>
	<?php
		}
	?>
</div>

            
