<h2>Data Structures Tutorial</h2>

<ul style="list-style-type: none;">
	<li><a href="<?= $this->url('datastructures', ['action' => 'index']) ?>" >Home</a></li>
	<li><a href="<?= $this->url('datastructures', ['action' => 'basics']) ?>">Basics</a></li>
	<li><a href="<?= $this->url('datastructures', ['action' => 'greedy']) ?>">Greedy</a></li>
	<li><a href="<?= $this->url('datastructures', ['action' => 'divideandconquer']) ?>">Divide And Conquer</a></li>
	<li><a href="<?= $this->url('datastructures', ['action' => 'dp']) ?>">Dynamic Programming</a></li>
</ul>