<h2>Big Data Tutorial</h2>

<ul style="list-style-type: none;">
	<li><a href="<?= $this->url('bigdata', ['action' => 'index']) ?>" >Home</a></li>
	<li><a href="<?= $this->url('bigdata', ['action' => 'overview']) ?>">Overview</a></li>
	<li><a href="<?= $this->url('bigdata', ['action' => 'methodology']) ?>">Methodology</a></li>
	<li><a href="<?= $this->url('bigdata', ['action' => 'analyst']) ?>">Big Data Analytics - Data Analyst</a></li>
	<li><a href="<?= $this->url('bigdata', ['action' => 'scientist']) ?>">Big Data Analytics - Data Scientist</a></li>
</ul>