<?php
	$title = 'Python';
	$this->headTitle($title);
?>

<div class="container">
	<div class="row">
		<div class="col-md-4">
			<div class="flex-row my-5">
				<div class="card-body">
					<?php
						echo $this->partial('python/python/links');
					?>
				</div>
			</div>
		</div>
		<div class="col-md-8">
			<div class="card-cust flex-row my-5">
				<div class="card-body">
                	<h1 class="card-title text-center">Python Tutorial</h1>
					<br>
					<p>Python is a general-purpose interpreted, interactive, object-oriented, and high-level programming language. It was created by Guido van Rossum during 1985- 1990. Like Perl, Python source code is also available under the GNU General Public License (GPL). This tutorial gives enough understanding on Python programming language.</p>

					<h3>Why to Learn Python?</h3>
					<p>Python is a high-level, interpreted, interactive and object-oriented scripting language. Python is designed to be highly readable. It uses English keywords frequently where as other languages use punctuation, and it has fewer syntactical constructions than other languages.
					</p>
					<p>
					Python is a MUST for students and working professionals to become a great Software Engineer specially when they are working in Web Development Domain. I will list down some of the key advantages of learning Python:
					</p>
					<ul>
						<li>
							<b>Python is Interpreted −</b> Python is processed at runtime by the interpreter. You do not need to compile your program before executing it. This is similar to PERL and PHP.
						</li>
						<li>
							<b>Python is Interactive −</b> You can actually sit at a Python prompt and interact with the interpreter directly to write your programs.
						</li>
						<li>
							<b> Python is Object-Oriented −</b> Python supports Object-Oriented style or technique of programming that encapsulates code within objects.
						</li>
					</ul>
					<h3>Characteristics of Python</h3>
					<ul>
						<li>It supports functional and structured programming methods as well as OOP.</li>
						<li>It can be used as a scripting language or can be compiled to byte-code for building large applications.</li>
						<li>It provides very high-level dynamic data types and supports dynamic type checking.</li>
						<li>It supports automatic garbage collection.</li>
						<li>It can be easily integrated with C, C++, COM, ActiveX, CORBA, and Java.</li>
					</ul>
					<h3>Applications of Python</h3>
					<ul>
						<li>
							<b> Easy-to-learn −</b> Python has few keywords, simple structure, and a clearly defined syntax. This allows the student to pick up the language quickly.
						</li>
						<li>
							<b>Easy-to-read −</b> Python code is more clearly defined and visible to the eyes.
						</li>
						<li>
							<b>Easy-to-maintain −</b> Python's source code is fairly easy-to-maintain.
						</li>
						<li>
							<b>A broad standard library −</b> Python's bulk of the library is very portable and cross-platform compatible on UNIX, Windows, and Macintosh.
						</li>
					</ul>
					<hr>
					<div>
					<a href="<?= $this->url('python', ['action' => 'overview']) ?>" style="float: right" >Next Page</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>