<h2>Python Basic Tutorial</h2>

<ul style="list-style-type: none;">
	<li><a href="<?= $this->url('python', ['action' => 'index']) ?>" >Home</a></li>
	<li><a href="<?= $this->url('python', ['action' => 'overview']) ?>">Overview</a></li>
	<li><a href="<?= $this->url('python', ['action' => 'basicsyntax']) ?>">Basic Syntax</a></li>
	<li><a href="<?= $this->url('python', ['action' => 'variabletypes']) ?>">Variable Types</a></li>
	<li><a href="<?= $this->url('python', ['action' => 'basicoperators']) ?>">Basic Opertors</a></li>
	<li><a href="<?= $this->url('python', ['action' => 'decisionmaking']) ?>">Decision Making</a></li>
	<li><a href="<?= $this->url('python', ['action' => 'loops']) ?>">Loops</a></li>
</ul>