<h2>DataScience Tutorial</h2>

<ul style="list-style-type: none;">
	<li><a href="<?= $this->url('datascience', ['action' => 'index']) ?>" >Home</a></li>
	<li><a href="<?= $this->url('datascience', ['action' => 'introduction']) ?>">Introduction</a></li>
	<li><a href="<?= $this->url('datascience', ['action' => 'pandas']) ?>">Pandas</a></li>
	<li><a href="<?= $this->url('datascience', ['action' => 'numpy']) ?>">Numpy</a></li>
	<li><a href="<?= $this->url('datascience', ['action' => 'scipy']) ?>">Scipy</a></li>
	<li><a href="<?= $this->url('datascience', ['action' => 'matplotlib']) ?>">Matplotlib</a></li>
</ul>

