<?php


$title = 'Edit Review';
$this->headTitle($title);
?>
<br><br><br>
<h1 class="text-center"><?= $this->escapeHtml($title) ?></h1>
<?php

$content = $form->get('content');
$content->setAttribute('class', 'form-control');
$content->setAttribute('placeholder', 'Content');
$content->setAttribute('required','required');

$course_id = $form->get('course_id');
$course_id->setAttribute('class', 'form-control');
$course_id->setAttribute('placeholder', 'Course ID');
$course_id->setAttribute('required','required');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('review', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($content) ?>
    <?= $this->formElement($content) ?>
    <?= $this->formElementErrors()->render($content, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($course_id) ?>
    <?= $this->formElement($course_id) ?>
    <?= $this->formElementErrors()->render($course_id, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();