
<div class="container-fluid" style="background-color: #336699">
	<div class="row">
    	<div style="height:450px; width: 100%">
			<center>
				<h1 class="text-white" style="color: black;margin-top: 150px; font-size: 50px;"><strong>REAL NAME: <?= $this->escapeHtml($identity->real_name) ?></strong></h1>
				<h4>USER NAME: <?= $this->escapeHtml($identity->username) ?></h4>
				<a href="<?= $this->url('course') ?>" class="btn btn-outline-warning">View All Courses</a>
			</center>
		</div> 
    </div>
</div>
