<div class="jumbotron">
    <h1 class="text-center">Welcome to Rtutor </h1>
    <p>
        You can browse for different types of courses and we are providing a vast number of courses. Also we will release more number of courses in future.
    </p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">Learn the latest skills </h2>
                <p>
                    like business analytics, graphic design, Python, and more
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">Get ready for a career </h2>
                <p>in high-demand fields like IT, AI and cloud engineering</p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">Upskill your organization</h2>
                <p>with on-demand training and development programs</p>
            </div>
        </div>
    </div>
</div>
