<?php
// module/Album/view/album/album/index.phtml:

$title = 'Posts';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('post', ['action' => 'add']) ?>">Add new post</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Content</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($posts as $post) : ?>
    <tr>
        <td><a href="<?= $this->url('post', ['action' => 'show', 'id' => $post->id]) ?>"><?= $this->escapeHtml($post->title) ?></a></td>
        <td><?= $this->escapeHtml($post->content) ?></td>
        <td>
            <a href="<?= $this->url('post', ['action' => 'edit', 'id' => $post->id]) ?>">Edit</a>
            <a href="<?= $this->url('post', ['action' => 'delete', 'id' => $post->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>