<h2>DL Tutorial</h2>

<ul style="list-style-type: none;">
	<li><a href="<?= $this->url('deeplearning', ['action' => 'index']) ?>" >Home</a></li>
	<li><a href="<?= $this->url('deeplearning', ['action' => 'introduction']) ?>">Introduction</a></li>
	<li><a href="<?= $this->url('deeplearning', ['action' => 'ann']) ?>">Artificial Neural Networks</a></li>
	<li><a href="<?= $this->url('deeplearning', ['action' => 'deepnn']) ?>">Deep Neural Networks</a></li>
	<li><a href="<?= $this->url('deeplearning', ['action' => 'graphs']) ?>">Computational Graphs</a></li>

</ul>