<?php
$title = 'Login';
$this->headTitle($title);
?>
<div class="login-form">
    <div class="login-heading">
        <h1 class="text-center"><?= $this->escapeHtml($title) ?></h1>
    </div>
    <?php
        $username = $form->get('username');
        $username->setAttribute('class', 'form-control');
        $username->setAttribute('placeholder', 'Username');
        $username->setAttribute('required','required');

        $password = $form->get('password');
        $password->setAttribute('class', 'form-control');
        $password->setAttribute('placeholder', 'Password');
        $password->setAttribute('required','required');

        $submit = $form->get('submit');
        $submit->setAttribute('class', 'btn btn-primary');

        $form->setAttribute('action', $this->url('user', ['action' => 'login']));
        $form->prepare();

        echo $this->form()->openTag($form);
    ?>
    <div class="form-group">
        <?= $this->formLabel($username) ?>
        <?= $this->formElement($username) ?>
        <?= $this->formElementErrors()->render($username, ['class' => 'help-block']) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($password) ?>
        <?= $this->formElement($password) ?>
        <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
    </div>

    <?php
    echo $this->formSubmit($submit);
    echo $this->formHidden($form->get('id'));
    echo $this->form()->closeTag();
    ?>
</div>
