<?php
use Laminas\Authentication\AuthenticationService;
$this->auth = new AuthenticationService();
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?=$this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false)?>

        <?=$this->headMeta()
->appendName('viewport', 'width=device-width, initial-scale=1.0')
->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
?>

        <!-- Le styles -->
        <?=$this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
->prependStylesheet($this->basePath('css/style.css'))
->prependStylesheet($this->basePath('css/bootstrap.min.css'))
?>

        <!-- Scripts -->
        <?=$this->headScript()?>
    </head>
    <body>
    <nav>
        <ul>
            <?php if ($this->auth->getIdentity()) {?>
            <li>
                <a href="<?=$this->url('user')?>">Welcome <?php echo $this->auth->getIdentity()->username ?> <span class="sr-only">(current)</span></a>
            </li>
            <li>
                <a href="<?=$this->url('todo')?>">Todo <span class="sr-only">(current)</span></a>
            </li>
            <li>
                <a href="<?=$this->url('user', ['action' => 'logout'])?>">Logout <span class="sr-only">(current)</span></a>
            </li>
            <?php } else {?>
            <li>
                <a href="<?=$this->url('user', ['action' => 'register'])?>">Register<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a href="<?=$this->url('user', ['action' => 'login'])?>">Login<span class="sr-only">(current)</span></a>
            </li>

            <?php }?>
        </ul>
    </nav>

        <?php
if ($this->flashMessenger()->hasMessages()) {
    ?>

            <div class="alert alert-success alert-dismissible fade show">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <?php
echo $this->flashMessenger()->render();
    ?>
            </div>
            <?php }?>
        <div class="container">
            <?=$this->content?>
        </div>
        <?=$this->inlineScript()
->prependFile($this->basePath('js/bootstrap.min.js'))
->prependFile($this->basePath('js/jquery-3.4.1.min.js'))?>
    </body>
</html>
